//
//  ViewController.swift
//  Example-Swift
//
//  Created by Dal Rupnik on 08/09/15.
//  Copyright © 2015 Dal Rupnik. All rights reserved.
//

import UIKit
import YesGraphSDK

class ViewController: UIViewController, YSGShareSheetDelegate {

    override func viewDidLoad() {
        
        // Set YesGraph client key
        
        if (YesGraph.shared().userId != nil)
        {
            self.setYSGclientKey(YesGraph.shared().userId!);
        }
        
        // for parse backend example, we set a user id '1234' if there is none set in YesGraph class
        else
        {
            self.setYSGclientKey("1234");
        }
        
        super.viewDidLoad()
    }
    
    @IBOutlet weak var introTextField: UITextField!
    @IBOutlet weak var additionalNotesTextView: UITextView!
    

    @IBAction func shareButtonTap(sender: UIButton) {
        let localSource = YSGLocalContactSource()
        localSource.contactAccessPromptMessage = "Share contacts with Example-Swift to invite friends?"
        
        let onlineSource = YSGOnlineContactSource(client: YSGClient(), localSource: localSource, cacheSource: YSGCacheContactSource())
        
        let inviteService = YSGInviteService(contactSource: onlineSource, userId: nil)
        
        let shareController = YSGShareSheetController(services: [YSGFacebookService(), YSGTwitterService(), inviteService], delegate: self)
        
        self.navigationController?.pushViewController(shareController, animated: true)
    }
    
    func shareSheetController(shareSheetController: YSGShareSheetController, messageForService service: YSGShareService, userInfo: [String : AnyObject]?) -> [String : AnyObject] {
        
        if let _ = service as? YSGFacebookService {
            return [YSGShareSheetMessageKey : "This message will be posted to Facebook."]
        }
        else if let _ = service as? YSGTwitterService {
            return [YSGShareSheetMessageKey : "This message will be posted to Twitter."]
        }
        else if let _ = service as? YSGInviteService {
            return [YSGShareSheetMessageKey : "This message will be posted to SMS."]
        }
        
        return [YSGShareSheetMessageKey : ""]
    }
    
    
    func setYSGclientKey(userId: NSString)
    {
        PFCloud.callFunctionInBackground("YGgetClientKey", withParameters: ["userId" : userId], target:self, selector: Selector("YSGclientKeyhandler:error:"))
    }
  
    func YSGclientKeyhandler(result: AnyObject!, error: NSError!) {
        if (error != nil) {
            let responseData : NSData = result.dataUsingEncoding(NSUTF8StringEncoding)!;
            
            do {
                let jsonDict = try NSJSONSerialization.JSONObjectWithData(responseData, options: NSJSONReadingOptions.MutableContainers) as? NSDictionary
                
                let YSGclientKey : NSString? = jsonDict!.objectForKey("client_key") as? NSString;
                if (YSGclientKey != nil)
                {
                    NSLog("Yes Graph client key: %@", YSGclientKey!);
                    YesGraph.shared().configureWithClientKey(YSGclientKey! as String);
                }
                
            }
            catch let error as NSError {
                NSLog(error.localizedDescription);
            }
            
        }
        else
        {
            NSLog("Error:%@", error.description);
        }
    }
}


// Javascript code that should be added to Parse.com Cloud Code section
//
// 'Authorization' in headers argument is a secret key generated by Yes Graph for our Example application
//

//Parse.Cloud.define("YGgetClientKey", function(request, response) {
//    var httpOptions = {
//    url: 'https://api.yesgraph.com/v0/client-key',
//    method: 'POST',
//    headers: {  'Authorization': 'Bearer live-WzEsMCwiRXhhbXBsZUFwcGxpY2F0aW9uIl0.COFZjA.iMmR8fez8lBRpoEtQS1DAyK8lZ4',
//        'Content-Type': 'application/json'
//    },
//    body: {'user_id': request.params.userId}
//    }
//
//    Parse.Cloud.httpRequest(httpOptions).then(
//                                              function(httpResponse) {
//                                                  response.success(httpResponse.text);
//                                              },
//                                              function(httpResponse) {
//                                                  console.log(httpResponse);
//                                                  var error = new Error();
//                                                  error.code = httpResponse.status;
//                                                  error.message = httpResponse.text;
//                                                  response.error(error);
//                                              }
//                                              );
//});
